---
- name: Copy the Package
  ansible.builtin.file:
    dest: "{{ dest_dir }}"
    state: directory
    mode: '0755'

- name: Copy the package to the target server
  ansible.builtin.copy:
    src: "/etc/ansible/{{ tar_files }}"
    dest: "{{ dest_dir }}"
    mode: '0644'

- name: Extract the file
  ansible.builtin.unarchive:
    src: "/var/tmp/{{ tar_files }}"
    dest: "{{ dest_dir }}"
    remote_src: true
