---
- name: Verify the Server Configuration
  ansible.builtin.ping:
  
- name: Update Server
  ansible.builtin.apt:
    update_cache: yes
- name: Configure timezone
  ansible.builtin.command:
    cmd: timedatectl set-timezone Asia/Kolkata

- name: Configure Directory
  ansible.builtin.file:
    path: /etc/ans_network
    state: directory
    owner: root
    group: root
    mode: '0755' 
