---
- name: Allow Ports 
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "{{ ssh_port }}"
    - "{{ http_port }}"
    - "{{ https_port }}"
- name: Deny Incoming traffic
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Allow Outgoing Traffic
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: Enable Firewall
  community.general.ufw:
    state: enabled
